<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Khan" failures="1" tests="17" name="Default test" time="0.384" errors="0" timestamp="9 Jan 2023 17:42:12 GMT">
  <testcase classname="TestPackage.MortgageLoan" name="MortgageLoanAPPLoging" time="0.045"/>
  <testcase classname="TestPackage.MortgageLoan" name="MortgageLoanBranch" time="0.004"/>
  <testcase classname="TestPackage.MortgageLoan" name="MortgageLoanWebloging" time="0.013"/>
  <testcase classname="TestPackage.FixedLoan" name="FixedLoanAPPLoging" time="0.004"/>
  <testcase classname="TestPackage.FixedLoan" name="FixedLoanBranch" time="0.007"/>
  <testcase classname="TestPackage.FixedLoan" name="FixedLoanWebloging" time="0.012"/>
  <testcase classname="TestPackage.FlexiLoan" name="FlexiLoanAPPLoging" time="0.01"/>
  <testcase classname="TestPackage.FlexiLoan" name="FlexiLoanBranch" time="0.004"/>
  <testcase classname="TestPackage.FlexiLoan" name="FlexiLoanWebloging" time="0.003"/>
  <testcase classname="TestPackage.CarLoan" name="CarLoanAPPLoging" time="0.002"/>
  <testcase classname="TestPackage.CarLoan" name="CarLoanBranch" time="0.01"/>
  <testcase classname="TestPackage.CarLoan" name="CarLoanWebloging" time="0.007"/>
  <testcase classname="TestPackage.BasicTest" name="Demo" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at org.testng.Assert.assertTrue(Assert.java:47)
	at TestPackage.BasicTest.Demo(BasicTest.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="TestPackage.BasicTest" name="getData" time="0.007"/>
  <testcase classname="TestPackage.SmartLaon" name="SmartLoanAPPLoging" time="0.032"/>
  <testcase classname="TestPackage.SmartLaon" name="SmartLoanBranch" time="0.011"/>
  <testcase classname="TestPackage.SmartLaon" name="SmartLoanWebloging" time="0.004"/>
</testsuite> <!-- Default test -->
